### ISSUE TITLE
This is not relevant to the repo, but it's the only way I can get contact to you via github

### ISSUE THREAD

**Issue by banana439monkey** [The-Unnamed-Engineer/Website-coding#3]
On the ask away forums, there's a user called theunnamedengineer. Is this you?

**Comment by The-Unnamed-Engineer** [comment]
Yes it is me however I haven't even logged on there since my other computer broke. I can be contacted via discord as 
The Unnamed Engineer#2858 or I will also try to log onto the ask away forums a little more. 
(I had totally forgotten they existed when my old computer died right at the beginning of the school year.)
